Repository DoGood-org/dogood-frontend, pull requests merged in 2025-06, with the labels that each got.

#38 add custom svgr-script
  package-lock.json
  package.json
  scripts/fix-line-endings.mjs
  scripts/svgr-conditional.mjs
  scripts/svgr-template.mjs
  scripts/watch-barrels.mjs
  src/app/[locale]/globals.css
  src/components/index.ts
  src/components/layout/header/NavDropdown.tsx
  src/components/layout/header/NavItemRenderer.tsx
  src/components/layout/header/Navigation.tsx
  src/components/main/about/AboutSection.tsx
  src/components/main/map/Map.tsx
  src/components/ui/Container.tsx
Labels: bug, enhancement

#39 change button-component
  src/app/[locale]/globals.css
  src/components/layout/header/NavButtons.tsx
  src/components/main/about/AboutAnimationTabs.tsx
  src/components/main/about/AboutSection.tsx
  src/components/ui/Button.tsx
Labels: enhancement

#40 done
  src/components/faq/ContactForm.tsx
  src/components/layout/footer/Footer.tsx
  src/components/main/Faq.tsx
Labels: enhancement

#41 upd
  src/components/main/Faq.tsx
Labels: duplicate

#44 change scroll in about-section
  src/components/layout/header/ThemeToggle.tsx
  src/components/main/about/AboutAnimationTabs.tsx
  src/components/main/about/AboutSection.tsx
Labels: bug, enhancement

#46 fix tasks component
  src/assets/svg/Vector.svg
  src/components/icons/Vector.tsx
  src/components/icons/index.ts
  src/components/main/HeroSection.tsx
  src/components/main/map/Map.tsx
  src/components/main/map/TaskItem.tsx
  src/lib/utils.ts
  src/types/mapType.ts
Labels: bug, enhancement

#48 Rebuild faq
  messages/en/faq.json
  src/app/[locale]/globals.css
  src/assets/images/faq/Lines.png
  src/assets/images/faq/linesBlack.png
  src/assets/svg/Line6.svg
  src/components/faq/ContactForm.tsx
  src/components/icons/Line6.tsx
  src/components/icons/index.ts
  src/components/main/Faq.tsx
Labels: enhancement

#51 change container styles
  src/app/[locale]/globals.css
  src/components/layout/header/Header.tsx
Labels: bug

#55 change variables
  documentation/styles.md
  src/app/[locale]/globals.css
  src/components/index.ts
Labels: documentation, enhancement

#58 About adaptive
  documentation/components.md
  messages/en/about.json
  src/app/[locale]/globals.css
  src/assets/images/about/about1.png
  src/assets/images/about/about2.png
  src/assets/images/about/about3.png
  src/assets/images/about/about4.png
  src/assets/images/about/donate1.png
  src/assets/images/about/donate2.png
  src/assets/images/about/donate3.png
  src/assets/images/about/donate4.png
  src/assets/images/about/grants1.png
  src/assets/images/about/grants2.png
  src/assets/images/about/grants3.png
  src/assets/images/about/grants4.png
  src/assets/images/about/import.ts
  src/assets/images/about/myDeeds1.png
  src/assets/images/about/myDeeds2.png
  src/assets/images/about/myDeeds3.png
  src/assets/images/about/myDeeds4.png
  src/assets/images/about/volunteer1.png
  src/assets/images/about/volunteer2.png
  src/assets/images/about/volunteer3.png
  src/assets/images/about/volunteer4.png
  src/assets/svg/ArrowRight.svg
  src/assets/svg/CaretDoubleRight.svg
  src/components/icons/ArrowRight.tsx
  src/components/icons/CaretDoubleRight.tsx
  src/components/icons/index.ts
  src/components/index.ts
  src/components/main/about/AboutAnimationTabs.tsx
  src/components/main/about/AboutImages.tsx
  src/components/main/about/AboutSection.tsx
  src/components/ui/Button.tsx
  src/components/ui/Container.tsx
  src/components/ui/LinkWithArrow.tsx
  src/hooks/useMediaQuery.ts
  src/hooks/useScrollToActive.ts
  src/hooks/useSwipe.ts
  src/lib/carouselUtils.ts
  src/types/aboutType.ts
  src/types/index.ts
Labels: documentation, enhancement

#56 Donate
  src/components/donate/DonateCard.tsx
  src/components/faq/ContactForm.tsx
  src/components/layout/footer/Footer.tsx
  src/components/layout/footer/SocialLinks.tsx
  src/components/main/Donate.tsx
  src/components/main/Faq.tsx
Labels: enhancement

#59 Change AboutImage
  src/components/main/about/AboutImages.tsx
Labels: enhancement
