Repository DoGood-org/dogood-frontend, pull requests merged in 2025-07, with the labels that each got.

#82 Burger menu
  messages/en/header.json
  package-lock.json
  package.json
  src/app/[locale]/globals.css
  src/assets/svg/CloseMenu.svg
  src/components/icons/CloseMenu.tsx
  src/components/icons/index.ts
  src/components/index.ts
  src/components/layout/header/AccountLinks.tsx
  src/components/layout/header/Header.tsx
  src/components/layout/header/LanguageSwitcher.tsx
  src/components/layout/header/ListDropdown.tsx
  src/components/layout/header/NavDropdown.tsx
  src/components/layout/header/NavItemRenderer.tsx
  src/components/layout/header/Navigation.tsx
  src/components/layout/header/SettingList.tsx
  src/components/layout/header/SpecialToggle.tsx
  src/components/layout/header/UserAvatar.tsx
  src/components/layout/mobileMenu/MobileDropdown.tsx
  src/components/layout/mobileMenu/MobileMenu.tsx
  src/components/layout/theme/ThemeInitializer.tsx
  src/components/layout/theme/ThemeToggle.tsx
  src/components/main/about/AboutAnimationTabs.tsx
  src/components/ui/Accordion.tsx
  src/components/ui/Button.tsx
  src/hooks/index.ts
  src/hooks/useIconComponents.tsx
  src/hooks/useMobileMenu.ts
  src/hooks/useSwipe.ts
  src/types/navigation.ts
Labels: enhancement

#83 Fixed bug burger menu
  src/components/index.ts
  src/components/layout/mobileMenu/MobileMenu.tsx
Labels: bug

#85 added features
  messages/en/faq.json
  package-lock.json
  package.json
  src/components/faq/ContactForm.tsx
Labels: enhancement

#86 Not found page
  messages/en/common.json
  messages/ua/common.json
  messages/ua/donate.json
  messages/ua/header.json
  messages/ua/howItWorks.json
  package-lock.json
  package.json
  src/app/[locale]/[...rest]/page.tsx
  src/app/[locale]/layout.tsx
  src/app/[locale]/not-found.tsx
  src/app/[locale]/test/page.tsx
  src/app/global-error.tsx
  src/app/layout.tsx
  src/app/not-found.tsx
  src/assets/images/notFound/errorDesck.png
  src/assets/images/notFound/errorMob.png
  src/assets/images/notFound/errorTabl.png
  src/assets/images/notFound/notFoundDesk.png
  src/assets/images/notFound/notFoundTabl.png
  src/assets/images/notFound/notFoundmob.png
  src/components/index.ts
  src/components/layout/not-found/ButtonPanel.tsx
  src/components/layout/not-found/NotFoundComponent.tsx
  src/components/main/hero/HeroContentLayer.tsx
  src/middleware.ts
  src/types/errorType.ts
Labels: enhancement

#87 Map no input
  messages/en/map.json
  src/app/[locale]/globals.css
  src/assets/images/map/default.png
  src/assets/images/map/my-pin.png
  src/components/icons/Animal.tsx
  src/components/icons/Faders.tsx
  src/components/icons/Food.tsx
  src/components/icons/GPSicon.tsx
  src/components/icons/Medicine.tsx
  src/components/icons/Nature.tsx
  src/components/index.ts
  src/components/main/map/AcceptShareLocationPopUp.tsx
  src/components/main/map/ButtonLocation.tsx
  src/components/main/map/ButtonZoom.tsx
  src/components/main/map/CustomControlContent.tsx
  src/components/main/map/CustomControlPanel.tsx
  src/components/main/map/Map.tsx
  src/components/main/map/PopUpContent.tsx
  src/components/main/map/StoreMapInstance.tsx
  src/components/main/map/TaskItem.tsx
  src/components/main/map/TasksList.tsx
  src/components/main/map/filters/CategoryFilter.tsx
  src/components/main/map/filters/CategoryIconList.tsx
  src/components/main/map/filters/CategoryLabel.tsx
  src/components/main/map/filters/DistanceFilter.tsx
  src/components/main/map/filters/FilterBadge.tsx
  src/components/main/map/filters/FilterBadges.tsx
  src/components/main/map/filters/FilterButton.tsx
  src/components/main/map/filters/FilterLabelCategory.tsx
  src/components/main/map/filters/Filters.tsx
  src/components/main/map/filters/FormSearch.tsx
  src/components/main/map/filters/LineDivider.tsx
  src/components/main/map/filters/SearchInput.tsx
  src/components/main/map/mockTasks.ts
  src/components/main/map/tasksPanel/AnimatedDrawler.tsx
  src/components/main/map/tasksPanel/ButtonOpenTasks.tsx
  src/components/main/map/tasksPanel/Description.tsx
  src/components/main/map/tasksPanel/TaskCategoryIconList.tsx
  src/components/main/map/tasksPanel/TaskCategoryLabel.tsx
  src/components/main/map/tasksPanel/TaskItem.tsx
  src/components/main/map/tasksPanel/TasksList.tsx
  src/components/portal/AnimatedModalWrapper.tsx
  src/hooks/useClickOutside.ts
  src/hooks/useLeafletControl.ts
  src/lib/coordinatesMatch.ts
  src/lib/debounce.ts
  src/lib/getGeolocationPromise.ts
  src/lib/mapUtils.ts
  src/lib/utils.ts
  src/types/mapType.ts
  src/zustand/selectors/availableCategoriesSelectors.ts
  src/zustand/selectors/filteredTasksSelectors.ts
  src/zustand/stores/filterStore.ts
  src/zustand/stores/mapStore.ts
  src/zustand/stores/taskStore.ts
Labels: enhancement

#88 Fix hero section
  src/app/[locale]/globals.css
  src/app/[locale]/not-found.tsx
  src/app/global-error.tsx
  src/assets/images/hero/PlanetDesck.png
  src/assets/images/hero/PlanetMob.png
  src/assets/images/hero/PlanetTabl.png
  src/assets/images/hero/planet.png
  src/components/layout/not-found/NotFoundComponent.tsx
  src/components/main/hero/HeroPlanetLayer.tsx
  src/components/main/hero/HeroSection.tsx
  src/components/main/hero/HeroSocialLink.tsx
Labels: bug

#93 New inputs contact
  src/components/faq/ContactForm.tsx
  src/components/faq/FormField.tsx
  src/components/index.ts
Labels: enhancement

#104 Account
  messages/de/account.json
  messages/de/reviews.json
  messages/en/account.json
  public/account/Razer.png
  public/account/amazon.png
  public/account/avatar.png
  public/account/org1.png
  public/account/org2.png
  public/account/rev1.png
  public/account/rev2.png
  public/account/rev3.png
  public/account/user.png
  public/account/userAvatar.png
  public/account/userNone.png
  src/app/[locale]/globals.css
  src/app/[locale]/page.tsx
  src/assets/svg/More.svg
  src/assets/svg/userLocate.svg
  src/components/account/accountPage/Account.tsx
  src/components/account/accountPage/AccountContentPanel.tsx
  src/components/account/accountPage/OrganizationItem.tsx
  src/components/account/accountPage/OrganizationList.tsx
  src/components/account/accountPage/ReviewItem.tsx
  src/components/account/accountPage/ReviewsList.tsx
  src/components/account/accountPage/UserAvatar.tsx
  src/components/account/accountPage/UserDescription.tsx
  src/components/account/accountPage/user.json
  src/components/icons/More.tsx
  src/components/icons/UserLocate.tsx
  src/components/icons/index.ts
  src/components/index.ts
  src/lib/formateDate.ts
  src/types/index.ts
  src/types/organization.ts
  src/types/reviewType.ts
Labels: bug, enhancement

#105 check loader
  src/app/[locale]/globals.css
  src/components/index.ts
  src/components/ui/ContentLoader.tsx
Labels: enhancement

#108 Main reviews
  documentation/styles.md
  messages/de/common.json
  messages/de/reviews.json
  messages/en/common.json
  messages/en/reviews.json
  public/reviews/bg-review-d.png
  public/reviews/bg-review-m.png
  public/reviews/bg-review-t.png
  src/app/[locale]/globals.css
  src/app/[locale]/page.tsx
  src/assets/images/reviews/bg-reviews-dark-d.png
  src/assets/images/reviews/bg-reviews-dark-m.png
  src/assets/images/reviews/bg-reviews-dark-t.png
  src/components/index.ts
  src/components/main/reviews/ReviewCard.tsx
  src/components/main/reviews/ReviewsSection.tsx
  src/components/main/reviews/reviews.json
  src/i18n/request.ts
  src/types/index.ts
  src/types/mainReviews.ts
Labels: documentation, enhancement
