Repository DoGood-org/dogood-frontend, pull requests merged in 2025-08, with the labels that each got.

#113 New reviews
  documentation/styles.md
  public/reviews/bg-review-d.png
  public/reviews/bg-review-m.png
  public/reviews/bg-review-t.png
  public/reviews/bg-reviews-d.png
  public/reviews/bg-reviews-m.png
  public/reviews/bg-reviews-t.png
  src/app/[locale]/globals.css
  src/components/main/reviews/ReviewCard.tsx
  src/components/main/reviews/ReviewsSection.tsx
  src/data/reviews.json
Labels: documentation, enhancement

#114 Fix news
  src/app/[locale]/globals.css
  src/components/main/faq/ContactForm.tsx
  src/components/main/news/NewsItem.tsx
  src/components/main/news/NewsList.tsx
  src/components/main/news/mockNews.ts
  src/components/main/reviews/ReviewsSection.tsx
  src/i18n/request.ts
Labels: bug

#112 Settings component
  messages/de/settings.json
  messages/en/settings.json
  next.config.ts
  package-lock.json
  package.json
  src/app/[locale]/globals.css
  src/assets/svg/CalendarDots.svg
  src/assets/svg/Discover.svg
  src/assets/svg/MakeBetter.svg
  src/assets/svg/SetPlus.svg
  src/assets/svg/SignUp.svg
  src/assets/svg/photo.svg
  src/components/account/navigation/PageContent.tsx
  src/components/account/settingsPage/DatePicker.tsx
  src/components/account/settingsPage/ImageUploadWithPreview.tsx
  src/components/account/settingsPage/InputField.tsx
  src/components/account/settingsPage/LocationSelect.tsx
  src/components/account/settingsPage/SelectField.tsx
  src/components/account/settingsPage/SettingsForm.tsx
  src/components/icons/Binoculars.tsx
  src/components/icons/CalendarDots.tsx
  src/components/icons/Discover.tsx
  src/components/icons/HandHeart.tsx
  src/components/icons/IcTwotonePlus.tsx
  src/components/icons/MakeBetter.tsx
  src/components/icons/NotePencil.tsx
  src/components/icons/Photo.tsx
  src/components/icons/SetPlus.tsx
  src/components/icons/SignUp.tsx
  src/components/icons/index.ts
  src/components/index.ts
  src/components/ui/Calendar.tsx
  src/components/ui/Label.tsx
  src/components/ui/Popover.tsx
  src/components/ui/Select.tsx
  src/components/ui/Textarea.tsx
  src/i18n/request.ts
  src/lib/utils.ts
  src/lib/validation/settingsSchema.ts
Labels: enhancement

#116 fixed account BottomNavigation
  src/components/account/navigation/BottomNavigation.tsx
Labels: bug

#120 Fix current account
  messages/de/tasks.json
  src/app/[locale]/account/AuthLayout.tsx
  src/app/[locale]/account/layout.tsx
  src/app/[locale]/account/page.tsx
  src/components/account/accountPage/AccountContent.tsx
Labels: bug

#122 fix bug with params into stripe-request
  src/app/api/payment-method/[id]/route.ts
Labels: bug

#128 Add universal fetcher
  src/lib/apiFetcher.ts
Labels: enhancement

#129 update apiFetcher and api, created 2 instanses for auth and guest
  src/components/index.ts
  src/lib/api.ts
  src/lib/apiFetcher.ts
Labels: enhancement
